### ISSUE TITLE
Some Apex charts not reandering properly 

### ISSUE THREAD

**Issue by dwalker93** [TailAdmin/free-nextjs-admin-dashboard#5]
I've no idea but only one apex chart rendering perferctly and others are not.

![image](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/65861708/a49555d6-9151-4726-916d-710f04cf8298)

giving error as 
![image](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/65861708/89163d84-d88e-4f2d-bb27-19762fc350af)

then i tried re exporting Apexchart component as like this.
![image](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/65861708/f76730b8-7d50-4099-b1f8-d015761d59fc)

but still no luck

**Comment by Coderamrin** [comment]
Hello @dwalker93, 

I cloned this repo and installed the dependencies. 
It seems to work fine here: 
![image](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/52592047/0361e4f0-1d3e-40d3-982e-f06f9608b086)

Have you tried to update something then the error occurred or it's like this after the installation?
Let me know when you introduced this bug so that I can help you out.

**Comment by dwalker93** [comment]
Ok. I double checked again. So problem cause because I updated next to v14. After that only the problem is showing up. If downgrade next to again v13 no errors occurring. Is there are way to fix this also in v14? thank you

**Comment by dwalker93** [comment]
Ok ok found the solution. You have to specify width and height in each Apexchart component. After that works fine.

**Comment by Coderamrin** [comment]
That's great. 
Let us know if you find any other issues.
